name: Publish
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:
jobs:
  build:
    if: github.repository == 'grails/grails-static-website'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: '11'
      - name: Publish Main Site
        run: ./publish.sh
        env:
          GITHUB_SLUG: grails/grails-static-website
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          # AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GRADLE_TASK: build
      - name: Publish Guides Site
        run: ./publish.sh
        env:
          GITHUB_SLUG: grails/grails-guides
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GRADLE_TASK: buildGuide
